# deployment/configs/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'django-monitor'

rule_files:
  - rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

scrape_configs:
  - job_name: 'django'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['${WEB_IP}:8000']
        labels:
          instance: 'web-server'

  - job_name: 'node'
    static_configs:
      - targets: ['${WEB_IP}:9100']
        labels:
          instance: 'web-server'